# Generated by Django 4.2.3 on 2023-07-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        default="Не заполнено",
                        max_length=50,
                        verbose_name="Название скила",
                    ),
                ),
                (
                    "opisanie",
                    models.CharField(
                        default="Не заполнено",
                        max_length=250,
                        verbose_name="Краткое описание",
                    ),
                ),
                ("full_text", models.TextField(verbose_name="Примеры реализации")),
            ],
        ),
    ]
